services:
    servicebus:
        image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
        ports:
            - "5672:5672"
            - "5300:5300"
        volumes:
          - ${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json
        environment:
            - SQL_SERVER=sqlserver
            - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
            - ACCEPT_EULA=${ACCEPT_EULA}
        depends_on:
            - sqlserver
        networks:
            sb-emulator:
                aliases:
                    - "sb-emulator"

    sqlserver:
        image: mcr.microsoft.com/azure-sql-edge:latest
        ports:
            - "1433:1433"
        environment:
            - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
            - ACCEPT_EULA=${ACCEPT_EULA}
        networks:
            sb-emulator:
                aliases:
                    - "sb-emulator"

networks:
  sb-emulator: